### Health Check
GET http://localhost:3000/health

### Logging Endpoint
POST http://localhost:3000/logging/ 
Content-Type: application/json

{
    "level": "INFO",
    "message": "This is a test log message"
}

### Filtering by level
GET http://localhost:3000/filtering/INFO

### Filtering by timestamp
GET http://localhost:3000/filtering/2026-09-21T04:00:00.00Z/2026-09-21T04:30:00.00Z

### Filtering by level and timestamp
GET http://localhost:3000/filtering/INFO/2026-09-21T04:00:00.00Z/2026-09-21T04:30:00.00Z

### Paginated Endpoint
GET http://localhost:3000/filtering?page=1&limit=2