### Health Check


GET http://loggingservice.com:31812/health

### Logging Endpoint

POST http://loggingservice.com:31812/logging/ 
Content-Type: application/json

{
    "level": "info",
    "message": "This is a test log message"
}

### Filtering Endpoint

GET http://loggingservice.com:31812/filtering/2026-09-21T04:00:00.00Z/2026-09-21T04:30:00.00Z

### Paginated Endpoint

GET http://loggingservice.com:31812/filtering?page=1&limit=2

ngrok http 192.168.49.2:80 --traffic-policy-file policy.yml