### Health Check
GET https://unfixable-sustained-onset.ngrok-free.dev/health

### Logging Endpoint
POST https://unfixable-sustained-onset.ngrok-free.dev/logging/ 
Content-Type: application/json

{
    "level": "INFO",
    "message": "This is a test log message"
}

### Filtering by level
GET https://unfixable-sustained-onset.ngrok-free.dev/filtering/INFO

### Filtering by timestamp
GET https://unfixable-sustained-onset.ngrok-free.dev/filtering/2026-09-22T17:10:49.016Z/2026-09-22T17:11:59.016Z

### Filtering by level and timestamp
GET https://unfixable-sustained-onset.ngrok-free.dev/filtering/INFO/2026-09-21T04:00:00.00Z/2026-09-21T04:30:00.00Z

### Paginated Endpoint
GET https://unfixable-sustained-onset.ngrok-free.dev/filtering?page=1&limit=10